"""initial

Revision ID: e0d78211f111
Revises: 
Create Date: 2026-05-14 06:28:30.962432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d78211f111'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('favicon_path', sa.String(), nullable=True),
    sa.Column('og_image_url', sa.String(), nullable=True),
    sa.Column('screenshot_path', sa.String(), nullable=True),
    sa.Column('screenshot_status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('is_dead', sa.Boolean(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('bookmark_tags',
    sa.Column('bookmark_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bookmark_id'], ['bookmarks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bookmark_id', 'tag_id')
    )
    op.execute("""
        CREATE VIRTUAL TABLE IF NOT EXISTS bookmarks_fts
        USING fts5(id UNINDEXED, title, url, description, notes, content='bookmarks', content_rowid='rowid')
    """)
    op.execute("""
        CREATE TRIGGER bookmarks_ai AFTER INSERT ON bookmarks BEGIN
            INSERT INTO bookmarks_fts(rowid, id, title, url, description, notes)
            VALUES (new.rowid, new.id, new.title, new.url, new.description, new.notes);
        END
    """)
    op.execute("""
        CREATE TRIGGER bookmarks_ad AFTER DELETE ON bookmarks BEGIN
            INSERT INTO bookmarks_fts(bookmarks_fts, rowid, id, title, url, description, notes)
            VALUES ('delete', old.rowid, old.id, old.title, old.url, old.description, old.notes);
        END
    """)
    op.execute("""
        CREATE TRIGGER bookmarks_au AFTER UPDATE ON bookmarks BEGIN
            INSERT INTO bookmarks_fts(bookmarks_fts, rowid, id, title, url, description, notes)
            VALUES ('delete', old.rowid, old.id, old.title, old.url, old.description, old.notes);
            INSERT INTO bookmarks_fts(rowid, id, title, url, description, notes)
            VALUES (new.rowid, new.id, new.title, new.url, new.description, new.notes);
        END
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS bookmarks_au")
    op.execute("DROP TRIGGER IF EXISTS bookmarks_ad")
    op.execute("DROP TRIGGER IF EXISTS bookmarks_ai")
    op.execute("DROP TABLE IF EXISTS bookmarks_fts")
    op.drop_table('bookmark_tags')
    op.drop_table('bookmarks')
    op.drop_table('tags')
    op.drop_table('collections')
    # ### end Alembic commands ###
